### ISSUE TITLE
Conventional commits do not run on main branch

### ISSUE THREAD

**Issue by jp-garduno** [UzielSolis/Software-Testing#1]
https://github.com/UzielSolis/Software-Testing/blob/8c2dc70f3ff1f88d5ef69a8074aee2fc5e1c2bed/.github/workflows/conventional_commits.yml#L5

Update the target branch to be main instead of master.

**Comment by UzielSolis** [comment]
fixed in: https://github.com/UzielSolis/Software-Testing/actions/runs/7700886533
